
services:
  app:
    container_name: app-nginx-aino-svc-conf
    networks:
      - app-network
    build:
      context: .
      dockerfile: ./Dockerfile
      target: phpapp
    env_file:
      - .env



  nginx:
    container_name: nginx-aino-svc-conf
    build:
      context: .
      dockerfile: ./Dockerfile
      target: nginxapp
    networks: [app-network]
    depends_on: [app]
    ports:
      - "8080:80"


networks:
  app-network:
    name: "app-network"
