name: deployment.yml
on:
  push:
    branches:
      - master


jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          REPOSITORY: https://${{ github.actor }}:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          APP_ENV: ${{ vars.APP_ENV }}
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_NAME: ${{ vars.APP_NAME }}
          APP_DEBUG: ${{ vars.APP_DEBUG }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_FROM_ADDRESS: ${{ secrets.MAIL_USERNAME }}
          MAIL_FROM_NAME: ${{ vars.APP_NAME }}
        with:
          command_timeout: 1h
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: REPOSITORY,GITHUB_REPOSITORY,APP_ENV,APP_NAME,APP_DEBUG,ADMIN_EMAIL,ADMIN_USERNAME,ADMIN_PASSWORD,MAIL_USERNAME,MAIL_PASSWORD,MAIL_FROM_ADDRESS,MAIL_FROM_NAME
          port: ${{ secrets.PORT }}
          script: |
              set -e

              REPOSITORY_NAME=$(basename "$GITHUB_REPOSITORY")
              APP_DIR="$REPOSITORY_NAME"
              DOCKER_BUILDKIT=1
              if [ -d "$APP_DIR/.git" ]; then
                echo "Updating existing repository..."
                cd "$APP_DIR"
                git pull --rebase -X ours origin master
              else
              echo "Cloning repository..."
                git clone "$REPOSITORY" "$APP_DIR"
                cd "$APP_DIR"
              fi
                sudo envsubst '
                $APP_ENV
                $APP_KEY
                $APP_NAME
                $APP_DEBUG
                $ADMIN_EMAIL
                $ADMIN_USERNAME
                $ADMIN_PASSWORD
                $MAIL_USERNAME
                $MAIL_PASSWORD
                $MAIL_FROM_ADDRESS
                $MAIL_FROM_NAME
                ' < .env.example > .env
                sudo mkdir -p database
                sudo touch database/database.sqlite
                sudo chown -R $USER:$USER database
                sudo docker compose -f prod.docker-compose.yml up -d

