name: Continuous Deployment
on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

          APP_ENV: ${{ vars.APP_ENV }}
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_NAME: ${{ vars.APP_NAME }}
          APP_DEBUG: ${{ vars.APP_DEBUG }}

          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_FROM_ADDRESS: ${{ secrets.MAIL_USERNAME }}
          MAIL_FROM_NAME: ${{ vars.APP_NAME }}

          GHCR_USERNAME: ${{ github.actor }}
          GHCR_PAT: ${{ secrets.GH_PAT }}

        with:
          command_timeout: 1h
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}

          envs: |
            GITHUB_REPOSITORY
            GHCR_USERNAME
            GHCR_PAT
            APP_ENV
            APP_KEY
            APP_NAME
            APP_DEBUG
            ADMIN_EMAIL
            ADMIN_USERNAME
            ADMIN_PASSWORD
            MAIL_USERNAME
            MAIL_PASSWORD
            MAIL_FROM_ADDRESS
            MAIL_FROM_NAME

          script: |
            set -e

            REPOSITORY_NAME=$(basename "$GITHUB_REPOSITORY")
            APP_DIR="/opt/$REPOSITORY_NAME"

            cd "$APP_DIR"

            echo "$GHCR_PAT" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin

            envsubst '
              $APP_ENV
              $APP_KEY
              $APP_NAME
              $APP_DEBUG
              $ADMIN_EMAIL
              $ADMIN_USERNAME
              $ADMIN_PASSWORD
              $MAIL_USERNAME
              $MAIL_PASSWORD
              $MAIL_FROM_ADDRESS
              $MAIL_FROM_NAME
            ' < .env.example > .env

            mkdir -p database
            touch database/database.sqlite
            chown -R $USER:$USER database

            docker compose -f prod.docker-compose.yml pull
            docker compose -f prod.docker-compose.yml up -d
